### ISSUE TITLE
Missing file 'level.tscn' or one of its dependencies

### ISSUE THREAD

**Issue by YounesSamatta** [Thunder-Engine-Dev/thunder-engine#4]
I Created a new private repository using from **te-template**, and then i cloned the  **thunder-engine** repository ( i tried both downloading as a zip and cloning using git bash) and i put everything from thunder-engine in "(project directory)/engine".
when i click on the 'level.tscn' i get the error popup : Missing file 'level.tscn' or one of its dependencies

**- Here's the debugger output:**
 . Attempt to open script 'res://engine/objects/core/player/scripts/player_camera_2d.gd' resulted in error 'File not found'.
 . Failed loading resource: res://engine/objects/core/player/scripts/player_camera_2d.gd. Make sure resources have been imported by opening the project in the editor at least once.
.  scene/resources/resource_format_text.cpp:283 - res://engine/scenes/level.tscn:22 - Parse Error: 
.  Failed loading resource: res://engine/scenes/level.tscn. Make sure resources have been imported by opening the project in the editor at least once.

**Comment by reflexguru** [comment]
Hello and thanks for trying out this project.

You can fix this issue by manually searching for this file and replacing the script dependency, this issue will be fixed later.

Also I want to warn you that this project is unfinished and it's not ready for production use yet.

**Comment by YounesSamatta** [comment]
yeah i managed to fix it by editing the scene dependency player_camera_2d.gd to res:\\engine\objects\players
anyway, Hoping your project goes well :)

**Comment by reflexguru** [comment]
feel free to check out our discord and talk with us directly anyway
