### ISSUE TITLE
Can't import to godot

### ISSUE THREAD

**Issue by YounesSamatta** [Thunder-Engine-Dev/thunder-engine#5]
there's no "project.godot" file

**Comment by YounesSamatta** [comment]
i cloned the template , but i couldn't figure out the use of the thunder engine repo,what am i supposed to do with it?

**Comment by looper231** [comment]
how did you clone it?

**Comment by YounesSamatta** [comment]
i cloned both repos with the github desktop client

**Comment by looper231** [comment]
Try following this video guide https://www.youtube.com/watch?v=802Ees7mnWM

**Comment by looper231** [comment]
> i cloned both repos with the github desktop client

Cloning the template isn't suited with the desktop client. You'd have to do it on terminal

**Comment by YounesSamatta** [comment]
Thanks for your help i managed to get it working but do i only need the template ? whats the use of this repo

**Comment by looper231** [comment]
You should read the readme of the template repo to understand its purpose
